api_key = 'PK0LS8DH7E4SSKU9YGW8'
api_secret = 'N2woRIuKz6pHCbeAVzPEHwjVTWsPmLZpFzP36nzK'
base_url = 'https://paper-api.alpaca.markets'
data_url = 'https://data.alpaca.markets/v2'
crypto_url = 'https://api.alternative.me/v2/ticker/Bitcoin/?convert=USD'
Support = 'https://pythonrepo.com/repo/alpacahq-alpaca-trade-api-python-python-third-party-apis-wrappers'