api_key = 'PKMHSHNH504427JJESEY'
api_secret = 'pbbAw1w8y3zy5t8Ax4gn3cj0aDIwIVfKjorJnQ79'
base_url = 'https://paper-api.alpaca.markets'
data_url = 'https://data.alpaca.markets/v2'
crypto_url = 'https://api.alternative.me/v2/ticker/Bitcoin/?convert=USD'
Support = 'https://pythonrepo.com/repo/alpacahq-alpaca-trade-api-python-python-third-party-apis-wrappers'