api_key = 'PK52T4UD1HGWBX8FJHPL'
api_secret = '3fiFX9xKVheheQER7LTL1tWyKH3q71ABU7U33qEU'
base_url = 'https://paper-api.alpaca.markets'
data_url = 'https://data.alpaca.markets/v2'
crypto_url = 'https://api.alternative.me/v2/ticker/Bitcoin/?convert=USD'
Support = 'https://pythonrepo.com/repo/alpacahq-alpaca-trade-api-python-python-third-party-apis-wrappers'